spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://192.168.1.1:3306/javeriana
    username: root
    password: Example132
    driver-class-name: com.mysql.cj.jdbc.Driver